### ISSUE TITLE
txkube.test.test_memory.NullAgencyTests.test_after_create sometimes fails because "Data generation is extremely slow"

### ISSUE THREAD

**Issue by exarkun** [LeastAuthority/txkube#180]
```

[ERROR]
Traceback (most recent call last):
Failure: testtools.testresult.real._StringException: Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/txkube/test/test_memory.py", line 65, in test_after_create
    def test_after_create(self, obj):
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/hypothesis/core.py", line 1048, in wrapped_test
    state.run()
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/hypothesis/core.py", line 727, in run
    sys.settrace(None)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/hypothesis/internal/conjecture/engine.py", line 435, in run
    self._run()
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/hypothesis/internal/conjecture/engine.py", line 770, in _run
    self.generate_new_examples()
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/hypothesis/internal/conjecture/engine.py", line 685, in generate_new_examples
    self.test_function(last_data)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/hypothesis/internal/conjecture/engine.py", line 270, in test_function
    self.record_for_health_check(data)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/hypothesis/internal/conjecture/engine.py", line 374, in record_for_health_check
    state.overrun_examples), HealthCheck.too_slow,)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/hypothesis/internal/healthcheck.py", line 38, in fail_health_check
    raise FailedHealthCheck(message, label)
hypothesis.errors.FailedHealthCheck: Data generation is extremely slow: Only produced 8 valid examples in 1.13 seconds (4 invalid ones and 0 exceeded maximum size). Try decreasing size of the data you're generating (with e.g.max_size or max_leaves parameters).
See https://hypothesis.readthedocs.io/en/latest/healthchecks.html for more information about this. If you want to disable just this health check, add HealthCheck.too_slow to the suppress_health_check settings for this test.
txkube.test.test_memory.NullAgencyTests.test_after_create
```

**Comment by exarkun** [comment]
This failure seems to depend on the CPU resources available when running the test.  Run the test on a slower machine (or a more contended machine) and correspondingly more wallclock time will pass for the same amount of data generation.  Therefore, the TravisCI build environment is particularly susceptible to _intermittently_ failing tests in this way because it provides test runs with a highly variable CPU resource.

Therefore, turn this check _off_ on CI.
