### ISSUE TITLE
KubernetesClientIntegrationTests.test_configmap is failing on Python 3

### ISSUE THREAD

**Issue by rodrigc** [LeastAuthority/txkube#185]
KubernetesClientIntegrationTests.test_configmap is failing on Python 3:

```
Traceback (most recent call last):
Failure: testtools.testresult.real._StringException: Empty attachments:
  eliot-log
twisted-log: {{{2018-04-20 08:05:36+0000 [-] /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/txkube/testing/_eliot.py:57: builtins.DeprecationWarning: add_destination is deprecated since 1.1.0. Use add_destinations instead.}}}
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/testtools/testcase.py", line 680, in _run_setup
    ret = self.setUp()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/txkube/testing/integration.py", line 792, in setUp
    self.kubernetes = get_kubernetes(self)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/txkube/test/test_memory.py", line 30, in get_kubernetes
    return memory_kubernetes()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/txkube/_memory.py", line 46, in memory_kubernetes
    return _MemoryKubernetes()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/txkube/_memory.py", line 63, in __init__
    self._resource = _kubernetes_resource(self, self.model)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/txkube/_memory.py", line 100, in _kubernetes_resource
    return _Kubernetes(memory_service, model).app.resource()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/klein/app.py", line 155, in __get__
    k = self._bound_klein_instances.get(instance)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/weakref.py", line 429, in get
    return self.data.get(ref(key),default)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/attr/_make.py", line 693, in hash_
    return hash(_attrs_to_tuple(self, attrs))
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/attr/_make.py", line 693, in hash_
    return hash(_attrs_to_tuple(self, attrs))
TypeError: unhashable type: 'version.Info'
txkube.test.test_memory.KubernetesClientIntegrationTests.test_configmap
```

**Comment by rodrigc** [comment]
Fixed in https://github.com/LeastAuthority/txkube/pull/169
